# Set an upstream server , nginx can proxy requests to

upstream java{
	server java-app:8080;
	}

#define the vitual server, how should nginx handle the incoming requests

server{
	listen 80;
	server_name 174.129.82.76;

	location / {
		proxy_pass http://java-app:8080;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_X_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
	}
}
